 rosi_simulation: 

  # possible values: true, false.
  simulation_rendering: true

  # possible values: true, false.
  velodyne_processing: true

  # possible values: true, false.
  kinect_processing: true

  # possible values: true, false.
  hokuyo_processing: true

  # ATTENTION: This feature is strictly visual and do not affect velodyne processing
  # possible values: true, false.
  hokuyo_lines: false

  # possible values: true, false
  ur5toolCam_processing: true

  fire_rendering: true
